#!/usr/bin/env python3
# Copyright 2026 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

"""Generate data_bifurcation.h from a bifurcation lattice file (no extra deps)."""

import os
import random
import struct
import sys


HEADER = """\
// Copyright 2026 ETH Zurich and University of Bologna.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// File generated by gen_bifurcation_data.py

"""


def float_hex(value):
    bits = struct.unpack(">I", struct.pack(">f", float(value)))[0]
    return "(float) 0X{:08X}".format(bits)


def write_array(name, typ, values, per_line=4):
    lines = [
        "{}{} __attribute__((aligned(4 * NUM_BANKS), section(\".l2\"))) {}[{}] = {{".format(
            typ, "", name, len(values)
        )
    ]
    row = "    "
    for i, value in enumerate(values):
        if typ == "float":
            token = float_hex(value) + ", "
        else:
            token = "(uint32_t) {}, ".format(int(value))
        row += token
        if (i + 1) % per_line == 0:
            lines.append(row.rstrip())
            row = "    "
    if row.strip():
        lines.append(row.rstrip().rstrip(","))
    lines.append("};\n")
    return "\n".join(lines)


def load_lattice(path):
    with open(path, "r") as f:
        tokens = [int(x) for x in f.read().split()]

    num_nodes = tokens[0]
    num_edges = tokens[1]
    edges = [tokens[2 + 3 * i : 2 + 3 * (i + 1)] for i in range(num_edges)]

    neighbors = [set() for _ in range(num_nodes)]
    for u, v, _w in edges:
        neighbors[u - 1].add(v - 1)
        neighbors[v - 1].add(u - 1)

    row_ptr = []
    col_idx = []
    offset = 0
    for i in range(num_nodes):
        row_ptr.append(offset)
        nbrs = sorted(neighbors[i])
        col_idx.extend(nbrs)
        offset += len(nbrs)
    row_ptr.append(offset)

    return num_nodes, num_edges, row_ptr, col_idx


def gen_initial_spins(num_nodes, seed):
    rng = random.Random(seed)
    x_init = []
    for _ in range(num_nodes):
        sample = rng.gauss(0.0, 1.0)
        if sample >= 0.0:
            x_init.append(1.0)
        else:
            x_init.append(-1.0)
    return x_init


def main():
    root = os.path.dirname(os.path.abspath(__file__))
    lattice_path = os.path.join(
        root, "..", "..", "matlab_scripts", "bifurcation", "g4096_lattice.txt"
    )
    out_path = os.path.join(root, "data_bifurcation.h")

    if len(sys.argv) > 1:
        lattice_path = sys.argv[1]
    if len(sys.argv) > 2:
        out_path = sys.argv[2]

    num_nodes, num_edges, row_ptr, col_idx = load_lattice(lattice_path)
    x_init = gen_initial_spins(num_nodes, seed=42)
    lattice_name = os.path.basename(lattice_path)

    body = HEADER
    body += '#define bifurcation_lattice_name "{}"\n'.format(lattice_name)
    body += "#define sb_a (15)\n"
    body += "#define sb_b (7.5)\n"
    body += "#define sb_c (0)\n"
    body += "#define num_iter (100)\n"
    body += "#define init_seed (42)\n"
    body += "#define num_nodes ({})\n".format(num_nodes)
    body += "#define num_edges ({})\n".format(num_edges)
    body += "#define optimal_cut ({})\n".format(num_edges)
    body += "#define csr_nnz ({})\n\n".format(len(col_idx))

    body += write_array("l2_row_ptr", "uint32_t", row_ptr)
    body += "\n"
    body += write_array("l2_col_idx", "uint32_t", col_idx)
    body += "\n"
    body += write_array("l2_x_init", "float", x_init)

    with open(out_path, "w") as f:
        f.write(body)

    print("Generated {}".format(out_path))


if __name__ == "__main__":
    main()
