function [x_o] = H0_SB(x_i,J_i,N,a,b,c,decay,noise_stream,offset)

    num_cores = 4;

    if mod(N,num_cores) ~= 0
        error('N must be divisible by 4');
    end

    spins_per_core = N/num_cores;

    x_o = zeros(N,1);


    % Core 1
    local_start = 1;
    local_stop = spins_per_core;

    x_o(local_start:local_stop) = leaf_SB( ...
        x_i, ...
        J_i(local_start:local_stop,:), ...
        offset+local_start, ...
        offset+local_stop, ...
        a,b,c,decay, ...
        noise_stream(local_start:local_stop));


    % Core 2
    local_start = spins_per_core+1;
    local_stop = 2*spins_per_core;

    x_o(local_start:local_stop) = leaf_SB( ...
        x_i, ...
        J_i(local_start:local_stop,:), ...
        offset+local_start, ...
        offset+local_stop, ...
        a,b,c,decay, ...
        noise_stream(local_start:local_stop));


    % Core 3
    local_start = 2*spins_per_core+1;
    local_stop = 3*spins_per_core;

    x_o(local_start:local_stop) = leaf_SB( ...
        x_i, ...
        J_i(local_start:local_stop,:), ...
        offset+local_start, ...
        offset+local_stop, ...
        a,b,c,decay, ...
        noise_stream(local_start:local_stop));


    % Core 4
    local_start = 3*spins_per_core+1;
    local_stop = N;

    x_o(local_start:local_stop) = leaf_SB( ...
        x_i, ...
        J_i(local_start:local_stop,:), ...
        offset+local_start, ...
        offset+local_stop, ...
        a,b,c,decay, ...
        noise_stream(local_start:local_stop));

end